CREATE DATABASE Cinema_Booking_System;
USE Cinema_Booking_System; 

CREATE TABLE Films (

	ID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(45) NOT NULL UNIQUE,
	length_min INT NOT NULL
);

CREATE TABLE Customers (

	ID INT PRIMARY KEY AUTO_INCREMENT,
	First_Name VARCHAR(45),
	Last_Name VARCHAR(45) NOT NULL,
	Email VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE Rooms (

	ID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(45) NOT NULL,
	No_Seats INT NOT NULL
);

CREATE TABLE Screenings (

	ID INT PRIMARY KEY AUTO_INCREMENT,
	Film_ID INT NOT NULL,
	Room_ID INT NOT NULL, 
	Start_Time DATETIME NOT NULL,
	FOREIGN KEY (Film_ID) REFERENCES Films(ID),
	FOREIGN KEY (Room_ID) REFERENCES Rooms(ID)
);

CREATE TABLE Seats (

	ID INT PRIMARY KEY AUTO_INCREMENT, 
	RowNo CHAR(1) NOT NULL,
	Number INT NOT NULL,
	Room_ID INT NOT NULL, 
	FOREIGN KEY (Room_ID) REFERENCES Rooms(ID)
);

CREATE TABLE Bookings (

	ID INT PRIMARY KEY AUTO_INCREMENT,
	Screening_ID INT NOT NULL, 
	Customer_ID INT NOT NULL,
	FOREIGN KEY (Screening_ID) REFERENCES Screenings(ID),
	FOREIGN KEY (Customer_ID) REFERENCES customers(ID)
);

CREATE TABLE Reserved_Seat (

	ID INT PRIMARY KEY AUTO_INCREMENT,
	Booking_ID INT NOT NULL,
	Seat_ID INT NOT NULL,
	FOREIGN KEY (Booking_ID) REFERENCES Bookings(ID),
	FOREIGN KEY (Seat_ID) REFERENCES Seats(ID)
);
